apiVersion: v1
kind: ConfigMap
metadata:
  name: html-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to My WebSite!</title>
    </head>
    <body>
    <h1>Welcome to My WebSite!</h1>
    <p>This file is delivered by ty-bnn.</p>
    <p><em>Thank you for coming My WebSite.</em></p>
    </body>
    </html>